from typing import Any, Dict

CONFIG: Dict[str, Any] = {
    "list_api": {
        "url": "https://bgwlgl.bbwport.com/api/train-sea-union/real/train/listRealTrainInfo.do",
        "method": "POST",
        "timeout": 30,
        "retries": 5,
        "retry_backoff_base": 1.5,
        "sleep_between_pages": 0.2,
        "headers": {
            "accept": "application/json, text/plain, */*",
            "content-type": "application/json;charset=UTF-8",
            "origin": "https://bgwlgl.bbwport.com",
            "referer": "https://bgwlgl.bbwport.com/",
            "user-agent": "Mozilla/5.0",
            "auth_token": "${AUTH_TOKEN}",
            "cookie": "${COOKIE}",
        },
        "auth_link_flow": {
            "enabled": False,
        },
        "payload_template": {
            "pageNumber": 0,
            "pageSize": 200,
            "params": {
                "realTrainCode": "",
                "startStation": "",
                "endStation": "",
                "endProvince": "",
                "lineCode": "",
                "lineName": "",
                "upOrDown": "上行",
                "departureDateStart": "",
                "loadingTimeStart": "",
                "loadingTimeEnd": "",
            },
            "sorts": [],
        },
        "pagination": {
            "page_param": "pageNumber",
            "page_size_param": "pageSize",
            "page_size": 200,
            "start_page": 0,
            "one_based": False,
            "max_pages": 10000,
            "rows_field": "rows",
            "total_field": "total",
            "total_pages_field": "totalPage",
        },
    },
    "export_api": {
        "url": "https://bgwlgl.bbwport.com/api/train-sea-union/bookingInfo/exportLoadedBox.do",
        "method": "POST",
        "timeout": 60,
        "retries": 3,
        "flag": "单表",
        "headers": {
            "accept": "application/json, text/plain, */*",
            "content-type": "application/json;charset=UTF-8",
            "origin": "https://bgwlgl.bbwport.com",
            "referer": "https://bgwlgl.bbwport.com/",
            "user-agent": "Mozilla/5.0",
            "auth_token": "${AUTH_TOKEN}",
            "cookie": "${COOKIE}",
        },
    },
    "run": {
        "target_day": "",
        "output_dir": "data",
        "output_filename_template": "export_loaded_box_{day}.xlsx",
        "save_sample_rows": False,
        "sample_rows_path": "sample_rows.json",
    },
    "processing": {
        "enabled": True,
        "consigner_field": "委托客户",
        "consigner_env_key": "CONSIGNOR_NAME",
        "actual_booker_field": "实际订舱客户",
        "actual_booker_exclude": "陆海新通道",
        "output_dir": "data/actual_booker",
        "sheet_name": "data",
        "output_template": "{actual_booker}.xlsx",
    },
    "login_api": {
        "enabled": True,
        "captcha": {
            "enabled": True,
            "value_env_key": "CAPTCHA_VALUE",
            "key_env_key": "CAPTCHA_KEY",
            "rs_id_env_key": "LOGIN_RS_ID",
            "url": "https://bgwlgl.bbwport.com/api/bgwl-cloud-center/random",
            "method": "GET",
            "timeout": 10,
            "headers": {
                "accept": "application/json, text/plain, */*",
                "origin": "https://bgwlgl.bbwport.com",
                "referer": "https://bgwlgl.bbwport.com/",
                "user-agent": "Mozilla/5.0",
            },
            "params": {"show": "${CAPTCHA_SHOW}"},
            "save_path": "data/captcha/latest.png",
            "retries": 3,
            "retry_sleep": 1,
            "response_type": "base64_json",
            "image_field": "randomCodeImage",
            "key_field": "captchaKey",
            "rs_id_field": "_rs_id",
        },
        "login": {
            "url": "https://bgwlgl.bbwport.com/api/bgwl-cloud-center/login.do",
            "method": "POST",
            "timeout": 15,
            "password_hash": "md5",
            "headers": {
                "accept": "application/json, text/plain, */*",
                "content-type": "application/json;charset=UTF-8",
                "user-agent": "Mozilla/5.0",
            },
            "params_template": {},
            "rs_id_param": "_rs_id",
            "random_code_param": "_randomCode_",
            "payload_template": {
                "username": "${LOGIN_USERNAME}",
                "password": "${LOGIN_PASSWORD}",
            },
            "captcha_field": "captcha",
            "captcha_key_field": "captchaKey",
        },
        "token_json_path": ["data", "token"],
        "token_env": "AUTH_TOKEN",
        "cookie_env": "COOKIE",
    },
}
